version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  chat:
    build:
      context: ./chat
      dockerfile: build/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - app-network

  notification:
    build:
      context: ./notification
      dockerfile: build/Dockerfile
    ports:
      - "8082:8080"
    networks:
      - app-network

  user:
    build:
      context: ./user
      dockerfile: build/Dockerfile
    ports:
      - "8083:8080"
    networks:
      - app-network

  user_subscription:
    build:
      context: ./user_subscription
      dockerfile: build/Dockerfile
    ports:
      - "8084:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge